import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-error-container': '#93000a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00174b',
        'on-secondary-fixed': '#00201d',
        'surface-container-highest': '#d3e4fe',
        'surface-container-lowest': '#ffffff',
        outline: '#76777d',
        'inverse-on-surface': '#eaf1ff',
        'inverse-surface': '#213145',
        'on-surface-variant': '#45464d',
        surface: '#f8f9ff',
        'on-tertiary-container': '#497cff',
        'secondary-fixed-dim': '#6bd8cb',
        'tertiary-fixed': '#dbe1ff',
        'surface-dim': '#cbdbf5',
        'secondary-fixed': '#89f5e7',
        primary: '#000000',
        'inverse-primary': '#bec6e0',
        'on-tertiary-fixed': '#00174b',
        error: '#ba1a1a',
        'surface-container-high': '#dce9ff',
        'surface-container': '#e5eeff',
        'primary-container': '#131b2e',
        'surface-container-low': '#eff4ff',
        'surface-tint': '#565e74',
        'on-primary-container': '#7c839b',
        'on-primary-fixed-variant': '#3f465c',
        'surface-variant': '#d3e4fe',
        'on-tertiary-fixed-variant': '#003ea8',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#131b2e',
        'on-secondary-container': '#006f66',
        'on-surface': '#0b1c30',
        background: '#f8f9ff',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#bec6e0',
        'tertiary-fixed-dim': '#b4c5ff',
        'on-background': '#0b1c30',
        secondary: '#006a61',
        tertiary: '#000000',
        'surface-bright': '#f8f9ff',
        'error-container': '#ffdad6',
        'secondary-container': '#86f2e4',
        'on-secondary': '#ffffff',
        'outline-variant': '#c6c6cd',
        'primary-fixed': '#dae2fd',
        'on-secondary-fixed-variant': '#005049',
        // Used by the institutional sign-in design (slate-200 / slate-300)
        'border-subtle': '#e2e8f0',
        'border-strong': '#cbd5e1',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-xl': '2rem',
        margin: '2rem',
        'gutter-mobile': '0.75rem',
        gutter: '1.5rem',
        'space-xs': '0.25rem',
        'space-2xl': '3rem',
        'margin-mobile': '1rem',
        'space-lg': '1.5rem',
      },
      fontFamily: {
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'timer-display': ['JetBrains Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'timer-display': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'code-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['22px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
