tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c6c6cd",
        "on-secondary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed": "#131b2e",
        "inverse-primary": "#bec6e0",
        "surface-bright": "#f8f9ff",
        "inverse-surface": "#213145",
        "secondary-fixed-dim": "#6bd8cb",
        "secondary-container": "#86f2e4",
        "on-background": "#0b1c30",
        "primary": "#000000",
        "surface-variant": "#d3e4fe",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface": "#f8f9ff",
        "primary-fixed": "#dae2fd",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-container": "#006f66",
        "on-error": "#ffffff",
        "on-surface": "#0b1c30",
        "on-primary-container": "#7c839b",
        "background": "#f8f9ff",
        "on-secondary-fixed-variant": "#005049",
        "tertiary-container": "#00174b",
        "tertiary": "#000000",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "tertiary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed": "#00174b",
        "primary-container": "#131b2e",
        "on-tertiary-container": "#497cff",
        "secondary": "#006a61",
        "on-primary": "#ffffff",
        "outline": "#76777d",
        "on-secondary-fixed": "#00201d",
        "secondary-fixed": "#89f5e7",
        "primary-fixed-dim": "#bec6e0",
        "on-surface-variant": "#45464d",
        "tertiary-fixed": "#dbe1ff",
        "surface-tint": "#565e74",
        "on-tertiary-fixed-variant": "#003ea8"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-md": "1rem",
        margin: "2rem",
        "gutter-mobile": "0.75rem",
        "space-2xl": "3rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1rem",
        "space-sm": "0.5rem",
        gutter: "1.5rem",
        "space-xl": "2rem"
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "display-lg": ["Plus Jakarta Sans"],
        "label-md": ["Inter"],
        "body-sm": ["Inter"],
        "code-sm": ["JetBrains Mono"],
        "headline-lg": ["Plus Jakarta Sans"],
        "timer-display": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"]
      }
    }
  }
};
