tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#00174b",
        "tertiary-fixed": "#dbe1ff",
        "tertiary": "#000000",
        "primary-fixed-dim": "#bec6e0",
        "tertiary-container": "#00174b",
        "on-tertiary-fixed-variant": "#003ea8",
        "surface": "#f8f9ff",
        "tertiary-fixed-dim": "#b4c5ff",
        "secondary-fixed-dim": "#6bd8cb",
        "error-container": "#ffdad6",
        "surface-tint": "#565e74",
        "primary": "#000000",
        "on-primary-container": "#7c839b",
        "on-secondary-fixed-variant": "#005049",
        "primary-container": "#131b2e",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#86f2e4",
        "on-background": "#0b1c30",
        "on-surface-variant": "#45464d",
        "on-secondary": "#ffffff",
        "surface-container": "#e5eeff",
        "on-secondary-container": "#006f66",
        "surface-container-low": "#eff4ff",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-high": "#dce9ff",
        "on-primary-fixed-variant": "#3f465c",
        "background": "#f8f9ff",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#00201d",
        "outline": "#76777d",
        "surface-bright": "#f8f9ff",
        "on-tertiary-container": "#497cff",
        "inverse-on-surface": "#eaf1ff",
        "outline-variant": "#c6c6cd",
        "surface-dim": "#cbdbf5",
        "inverse-surface": "#213145",
        "surface-container-highest": "#d3e4fe",
        "inverse-primary": "#bec6e0",
        "on-surface": "#0b1c30",
        "on-primary-fixed": "#131b2e",
        "secondary-fixed": "#89f5e7",
        "secondary": "#006a61",
        "surface-variant": "#d3e4fe",
        "primary-fixed": "#dae2fd"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "gutter-mobile": "0.75rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1rem",
        gutter: "1.5rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-2xl": "3rem",
        "space-xl": "2rem",
        margin: "2rem"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-sm": ["Inter"],
        "label-sm": ["Inter"],
        "code-sm": ["JetBrains Mono"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "timer-display": ["JetBrains Mono"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "code-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "timer-display": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    }
  }
};
