import Icon from '../Icon.jsx';
import Modal from '../Modal.jsx';

export default function RevokeStaffModal({ member, onCancel, onConfirm }) {
  return (
    <Modal open={Boolean(member)} onClose={onCancel} labelledBy="revoke-title" paddingClass="p-space-xl">
      <div className="flex flex-col">
        <div className="w-12 h-12 rounded-full bg-error-container flex items-center justify-center text-error mb-space-md">
          <Icon name="gavel" className="text-[26px]" />
        </div>
        <h3 id="revoke-title" className="font-headline-md text-headline-md font-bold text-on-surface">
          Remove Staff Member?
        </h3>
        <p className="font-body-md text-body-md text-on-surface-variant mt-2 leading-relaxed">
          Are you sure you want to revoke exam portal access for{' '}
          <span className="font-semibold text-on-surface">{member?.name}</span>? This action will disable question
          paper drafting, revoke grading permissions, and immediately terminate any active node sessions.
        </p>
        <div className="mt-space-md p-space-sm rounded-lg bg-surface-container-low flex items-center gap-2">
          <Icon name="info" className="text-outline text-[18px]" />
          <span className="font-code-sm text-code-sm text-on-surface-variant">
            Historical audit logs generated by this user will be preserved.
          </span>
        </div>
        <div className="flex items-center justify-end gap-space-sm mt-space-xl">
          <button
            type="button"
            onClick={onCancel}
            className="px-4 py-2 rounded-lg bg-surface text-on-surface font-label-md text-label-md hover:bg-surface-container transition-colors"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={onConfirm}
            className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg bg-error text-on-error font-label-md text-label-md shadow-sm hover:opacity-90 transition-opacity"
          >
            <Icon name="person_remove" className="text-[16px]" />
            Revoke Access
          </button>
        </div>
      </div>
    </Modal>
  );
}
